services:
  webapp:
    build:
      dockerfile: streamlit.dockerfile
    container_name: webapp
    ports:
      - "8501:8501"
  api:
    build:
      dockerfile: fastapi.dockerfile
    container_name: api
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webapp
      - api
    ports:
      - "5000:80"